ICP-49 - Generate variety of error codes in fake data
riskfocus/cat-reporting-specs pull request #5
Opened 2021-01-29 15:42 UTC by SergeyRiskfocus

2021-01-29 17:44 UTC, rfvermut commented
No idea what to look for. Ask @kamikaze or @rf-KMurthy

2021-02-01 13:46 UTC, kamikaze requested changes

2021-02-01 13:46 UTC, kamikaze commented on src/cat_reporting_specs/generator.py
> +                        error_writer.writerow([choice((randrange(2016, 2068), randrange(2070, 2078),
randrange will not return a string. make all elemtent type to be the same

2021-02-01 13:46 UTC, kamikaze commented on src/cat_reporting_specs/generator.py
> +                        error_writer.writerow([choice((randrange(2016, 2068), randrange(2070, 2078),
why not randint() instead of randrange() ?

2021-02-01 14:59 UTC, kamikaze approved these changes

2021-02-01 15:19 UTC, merged